name: Build SefaAi Booster APK Clean
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Java Setup
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Install Android SDK & NDK
      uses: android-actions/setup-android@v3
      with:
        log-accepted-android-sdk-licenses: false

    - name: Install Android Component Sefa
      run: |
        sdkmanager --install "platform-tools" "build-tools;33.0.1" "platforms;android-33" "ndk;25.2.9519653"

    - name: Install System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git zip unzip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev libssl-dev libreadline-dev libffi-dev libsqlite3-dev sqlite3 bzip2 libbz2-dev

    - name: Install Buildozer and Cython
      run: |
        pip install --upgrade pip
        pip install "cython<3.0.0" buildozer kivy

    - name: Run Buildozer Android Debug
      run: |
        buildozer android debug
      env:
        BUILDOZER_WARN_ON_ROOT: 0
        ANDROID_SDK_HOME: /usr/local/lib/android/sdk
        ANDROID_NDK_HOME: /usr/local/lib/android/sdk/ndk/25.2.9519653

    - name: Upload Compiled APK
      uses: actions/upload-artifact@v4
      with:
        name: sefaai-gamebooster-clean
        path: bin/*.apk
        
